### ISSUE TITLE
addon pauses video when skipping intro

### ISSUE THREAD

**Issue by kolnischer** [malexanderboyd/ComfyFlix#2]
when skipping the intro on at least the Office, the video gets paused.

**Comment by markbolster12** [comment]
Yea I have seen this happen also. Not sure it's for only certain shows...

**Comment by malexanderboyd** [comment]
Thanks! I'll check this out!

Edit: 

Do you mind providing a bit more context? I can't seem to reproduce on 3.4.2.

**Comment by malexanderboyd** [comment]
Should be fixed in #3  (v3.5.0) -- Could you confirm when available and close the issue if so?

**Comment by ghost** [comment]
Nope, problem still persists in v3.5.0. - watching the Brooklyn Nine Nine, ComfyFlix skips intro and then pauses the video every time.

**Comment by malexanderboyd** [comment]
Hi all, I'm unable to reproduce locally, however, I wanted to make sure you are seeing the same time of button.

Mine looks like this: https://imgur.com/a/UGouybM

Does yours look similar?

**Comment by ghost** [comment]
Good news is that the "skip intro" feature does not pause the video anymore.
Bad news is that the "skip intro automatically" feature does no longer exist.

Watching Friends now - ComfyFlix just lets the into play in full.
It skips to the next video alright (after like 3 seconds). I am pretty sure my next video button looks similar.

**Comment by kolnischer** [comment]
Yay! Thank you so much!
